# Orquestación para el monorepo de Microfrontends y API
# Usa el Dockerfile Multietapa para construir cada servicio de forma eficiente.
services:
  # 1. API Service (Backend)
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-runtime # Usa la etapa de ejecución de la API
      args:
        APP_NAME: api
    ports:
      - "3001:3001"
    restart: always

  # 2. REMOTO: LOGIN
  login:
    build:
      context: .
      dockerfile: Dockerfile
      target: mfe-runtime
      args:
        APP_NAME: login
    ports:
      - "4201:80"
    restart: always

  # 3. REMOTO: BANNER
  banner:
    build:
      context: .
      dockerfile: Dockerfile
      target: mfe-runtime
      args:
        APP_NAME: banner # Este valor mapea a apps/banner y dist/banner
    ports:
      - "4202:80"
    restart: always

  # 4. REMOTO: MEMBER
  member:
    build:
      context: .
      dockerfile: Dockerfile
      target: mfe-runtime
      args:
        APP_NAME: member
        DIST_DIR: members
    ports:
      - "4203:80"
    restart: always

  # 5. HOST - (Contenedor Principal)
  host:
    build:
      context: .
      dockerfile: Dockerfile
      target: mfe-runtime
      args:
        APP_NAME: host
    ports:
      - "4200:80"
    depends_on:
      - api # Dependencia de la API
      - login
      - banner
      - member # Asegúrate de que todos los remotos estén aquí
    restart: always
